ossido refactor

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -35,25 +35,25 @@ jobs:
 
       - name: Check if the container is running
         run: |
-          docker ps --filter "name=tuono-source-container" --format "table {{.Names}}\t{{.Status}}"
-          if ! docker ps --filter "name=tuono-source-container" --format "{{.Status}}" | grep -q "Up"; then
-            echo "Error: Container 'tuono-source-container' is not running."
+          docker ps --filter "name=ossido-source-container" --format "table {{.Names}}\t{{.Status}}"
+          if ! docker ps --filter "name=ossido-source-container" --format "{{.Status}}" | grep -q "Up"; then
+            echo "Error: Container 'ossido-source-container' is not running."
             exit 1
           fi
 
       - name: Check commands inside container
         run: |
-          docker exec tuono-source-container pnpm --version || { echo "Error: pnpm is not available."; exit 1; }
-          docker exec tuono-source-container tuono --version || { echo "Error: tuono is not available."; exit 1; }
+          docker exec ossido-source-container pnpm --version || { echo "Error: pnpm is not available."; exit 1; }
+          docker exec ossido-source-container ossido --version || { echo "Error: ossido is not available."; exit 1; }
 
       - name: Run cargo test
-        run: docker exec tuono-source-container cargo test
+        run: docker exec ossido-source-container cargo test
 
-      - name: Install node dependencies in each tuono's sub-projets
-        run: docker exec tuono-source-container bash -c 'for dir in /tuono/packages/*; do [ -d "$dir" ] && (cd "$dir" && yes | pnpm install --frozen-lockfile); done'
+      - name: Install node dependencies in each ossido's sub-projets
+        run: docker exec ossido-source-container bash -c 'for dir in /ossido/packages/*; do [ -d "$dir" ] && (cd "$dir" && yes | pnpm install --frozen-lockfile); done'
 
       - name: Run pnpm test
-        run: docker exec tuono-source-container pnpm test
+        run: docker exec ossido-source-container pnpm test
 
       - name: Tear Down Docker Compose
         if: always()
