fix: CI fixes

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -43,17 +43,14 @@ jobs:
 
       - name: Check commands inside container
         run: |
-          docker exec ossido-source-container pnpm --version || { echo "Error: pnpm is not available."; exit 1; }
+          docker exec ossido-source-container bun --version || { echo "Error: bun is not available."; exit 1; }
           docker exec ossido-source-container ossido --version || { echo "Error: ossido is not available."; exit 1; }
 
       - name: Run cargo test
         run: docker exec ossido-source-container cargo test
 
-      - name: Install node dependencies in each ossido's sub-projets
-        run: docker exec ossido-source-container bash -c 'for dir in /ossido/packages/*; do [ -d "$dir" ] && (cd "$dir" && yes | pnpm install --frozen-lockfile); done'
-
-      - name: Run pnpm test
-        run: docker exec ossido-source-container pnpm test
+      - name: Run bun test
+        run: docker exec ossido-source-container bun run test
 
       - name: Tear Down Docker Compose
         if: always()
